# Generated by Django 2.2.10 on 2020-04-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_remove_logcreatedediteddeleted_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='logger',
            name='user_name',
        ),
    ]
